// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// BayesianCART
List BayesianCART(NumericMatrix x, IntegerVector y, NumericVector V, NumericVector a, NumericVector candidate_dose, int cat_num, bool standardization, int burnin, int Length, int every, int nChain, double size, double shape, double T0, std::vector<double> proprob, String prior_leaf, int MinimumLeafSize, unsigned int seed, int MinLeaf);
RcppExport SEXP _IndividualDosing_BayesianCART(SEXP xSEXP, SEXP ySEXP, SEXP VSEXP, SEXP aSEXP, SEXP candidate_doseSEXP, SEXP cat_numSEXP, SEXP standardizationSEXP, SEXP burninSEXP, SEXP LengthSEXP, SEXP everySEXP, SEXP nChainSEXP, SEXP sizeSEXP, SEXP shapeSEXP, SEXP T0SEXP, SEXP proprobSEXP, SEXP prior_leafSEXP, SEXP MinimumLeafSizeSEXP, SEXP seedSEXP, SEXP MinLeafSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type V(VSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type candidate_dose(candidate_doseSEXP);
    Rcpp::traits::input_parameter< int >::type cat_num(cat_numSEXP);
    Rcpp::traits::input_parameter< bool >::type standardization(standardizationSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type Length(LengthSEXP);
    Rcpp::traits::input_parameter< int >::type every(everySEXP);
    Rcpp::traits::input_parameter< int >::type nChain(nChainSEXP);
    Rcpp::traits::input_parameter< double >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type T0(T0SEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type proprob(proprobSEXP);
    Rcpp::traits::input_parameter< String >::type prior_leaf(prior_leafSEXP);
    Rcpp::traits::input_parameter< int >::type MinimumLeafSize(MinimumLeafSizeSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type MinLeaf(MinLeafSEXP);
    rcpp_result_gen = Rcpp::wrap(BayesianCART(x, y, V, a, candidate_dose, cat_num, standardization, burnin, Length, every, nChain, size, shape, T0, proprob, prior_leaf, MinimumLeafSize, seed, MinLeaf));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_IndividualDosing_BayesianCART", (DL_FUNC) &_IndividualDosing_BayesianCART, 19},
    {NULL, NULL, 0}
};

RcppExport void R_init_IndividualDosing(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
