# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BayesianCART <- function(x, y, cat_num, standardization, burnin, Length, every, nChain, size, shape, V, prior_leaf = "uniform", MinimumLeafSize = 1L, seed = 123L) {
    .Call(`_BayesTreeMCMC_BayesianCART`, x, y, cat_num, standardization, burnin, Length, every, nChain, size, shape, V, prior_leaf, MinimumLeafSize, seed)
}

