# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BayesianCART <- function(x, y, V, a, candidate_dose, cat_num, standardization, burnin, Length, every, nChain, size, shape, T0, prior_leaf = "uniform", MinimumLeafSize = 1L, seed = 123L, MinLeaf = 30L) {
    .Call(`_IndividualDosing_BayesianCART`, x, y, V, a, candidate_dose, cat_num, standardization, burnin, Length, every, nChain, size, shape, T0, prior_leaf, MinimumLeafSize, seed, MinLeaf)
}

GCBPS <- function(x, y) {
    .Call(`_IndividualDosing_GCBPS`, x, y)
}

GAM <- function(a, ps, y, a_out) {
    .Call(`_IndividualDosing_GAM`, a, ps, y, a_out)
}

